name: ResidPCA_Toolkit
channels:
  - conda-forge
  - defaults
dependencies:
  - anndata=0.9.1
  - appnope=0.1.2
  - archspec=0.2.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - boltons=23.0.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.23.0
  - ca-certificates=2023.11.17
  - cached-property=1.5.2
  - cached_property=1.5.2
  - certifi=2023.11.17
  - cffi=1.16.0
  - charset-normalizer=3.3.2
  - colorama=0.4.6
  - comm=0.1.2
  - conda=23.11.0
  - conda-libmamba-solver=23.11.1
  - conda-package-handling=2.2.0
  - conda-package-streaming=0.9.0
  - contourpy=1.0.5
  - cycler=0.12.1
  - debugpy=1.6.7
  - decorator=5.1.1
  - distro=1.8.0
  - entrypoints=0.4
  - executing=0.8.3
  - fmt=10.1.1
  - fonttools=4.46.0
  - freetype=2.12.1
  - get-annotations=0.1.2
  - giflib=5.2.1
  - h5py=3.10.0
  - hdf5=1.14.2
  - icu=73.2
  - idna=3.6
  - importlib-metadata=7.0.0
  - importlib-resources=6.1.1
  - importlib_resources=6.1.1
  - ipykernel=6.25.0
  - ipython=8.12.2
  - jedi=0.18.1
  - joblib=1.3.2
  - jpeg=9e
  - jsonpatch=1.33
  - jsonpointer=2.4
  - jupyter_client=7.4.9
  - jupyter_core=5.5.0
  - kiwisolver=1.4.5
  - krb5=1.21.2
  - lcms2=2.12
  - lerc=3.0
  - libaec=1.1.2
  - libarchive=3.7.2
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.5.0
  - libcxx=16.0.6
  - libdeflate=1.17
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=13.2.0
  - libiconv=1.17
  - liblapack=3.9.0
  - libllvm14=14.0.6
  - libmamba=1.5.4
  - libmambapy=1.5.4
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsolv=0.7.27
  - libssh2=1.11.0
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxml2=2.11.6
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - llvmlite=0.41.1
  - lz4-c=1.9.4
  - lzo=2.10
  - mamba=1.5.4
  - matplotlib-base=3.7.3
  - matplotlib-inline=0.1.6
  - menuinst=2.0.0
  - munkres=1.1.4
  - natsort=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - networkx=2.8.8
  - numba=0.58.1
  - numpy=1.24.4
  - openjpeg=2.5.0
  - openssl=3.2.0
  - packaging=23.2
  - pandas=2.0.3
  - parso=0.8.3
  - patsy=0.5.4
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3.1
  - platformdirs=4.1.0
  - pluggy=1.3.0
  - pooch=1.8.0
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pybind11-abi=4
  - pycosat=0.6.6
  - pycparser=2.21
  - pygments=2.15.1
  - pynndescent=0.5.11
  - pyparsing=3.1.1
  - pysocks=1.7.1
  - python=3.8.18
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.8
  - pytz=2023.3.post1
  - pyzmq=25.1.0
  - readline=8.2
  - reproc=14.2.4.post0
  - reproc-cpp=14.2.4.post0
  - requests=2.31.0
  - ruamel.yaml=0.18.5
  - ruamel.yaml.clib=0.2.7
  - scikit-learn=1.3.2
  - scipy=1.10.1
  - session-info=1.0.0
  - setuptools=68.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - statsmodels=0.14.0
  - stdlib-list=0.8.0
  - tbb=2021.10.0
  - threadpoolctl=3.2.0
  - tk=8.6.12
  - tornado=6.3.3
  - tqdm=4.66.1
  - traitlets=5.7.1
  - typing_extensions=4.8.0
  - umap-learn=0.5.5
  - unicodedata2=15.1.0
  - urllib3=2.1.0
  - wcwidth=0.2.5
  - wheel=0.41.2
  - xz=5.4.5
  - yaml-cpp=0.8.0
  - zeromq=4.3.4
  - zipp=3.17.0
  - zlib=1.2.13
  - zstandard=0.22.0
  - zstd=1.5.5
  - pip:
    - biothings-client==0.3.1
    - et-xmlfile==1.1.0
    - gseapy==1.1.1
    - igraph==0.10.8
    - leidenalg==0.10.1
    - mygene==3.2.2
    - openpyxl==3.1.2
    - pyreadr==0.5.0
    - scanpy==1.9.8
    - seaborn==0.13.2
    - texttable==1.7.0
    - upsetplot==0.9.0
